-- double check for relevance performed_via_github_app, active_lock_reason, closed_at
-- these cols have all zeros so far
-- sub_issues_summary_total,
--	sub_issues_summary_completed,
--	sub_issues_summary_percent_completed,
--	issue_dependencies_summary_blocked_by,
--	issue_dependencies_summary_total_blocked_by,
--	issue_dependencies_summary_blocking,
--	issue_dependencies_summary_total_blocking,
SELECT
	url,
	repository_url,
	labels_url,
	comments_url,
	events_url,
	html_url,
	issue_id,
	node_id,
	issue_number,
	title,
	labels_json,
	issue_state,
	issue_locked,
	assignees_json,
	milestone_json,
	issue_comments,
	created_at::TIMESTAMPTZ,
	updated_at::TIMESTAMPTZ,
	closed_at::TIMESTAMPTZ,
	author_association,
	active_lock_reason,
	body,
	timeline_url,
	performed_via_github_app,
	state_reason,
	repo_id,
	sub_issues_summary_total,
	sub_issues_summary_completed,
	sub_issues_summary_percent_completed,
	issue_dependencies_summary_blocked_by,
	issue_dependencies_summary_total_blocked_by,
	issue_dependencies_summary_blocking,
	issue_dependencies_summary_total_blocking,
	reaction_total_count,
	reaction_plus,
	reaction_minus,
	reaction_laugh,
	reaction_hooray,
	reaction_confused,
	reaction_heart,
	reaction_rocket,
	reaction_eyes,
	assignee_id,
	assignee_login,
	assignee_type,
	assignee_site_admin,
	closed_by_id,
	closed_by_login,
	closed_by_type,
	closed_by_site_admin
FROM issues
