-- ignore gravater_id all nulls
-- convert date columns to time stamp with time zone
SELECT
	login,
	user_id,
	node_id,
	avatar_url,
	url, 
	html_url,
	followers_url,
	following_url,
	gists_url,
	starred_url,
	subscriptions_url,
	organizations_url,
	repos_url,
	events_url,
	received_events_url,
	user_type,
	user_view_type,
	site_admin,
	user_name,
	company,
	blog,
	user_location,
	email,
	hireable,
	bio,
	twitter_username,
	public_repos,
	public_gists,
	followers,
	user_following,
	created_at::TIMESTAMPTZ,
	updated_at::TIMESTAMPTZ
FROM users
