-- 01_create_tables.sql
-- Creates PostgreSQL staging tables for GitHub REST API data.
-- Tables: users, repos, commits, issues.
--
-- Design notes:
-- - These are staging tables, so most timestamp fields are stored as TEXT first.
-- - JSONB is used for repeated/nested structures such as labels, assignees, and milestones.
-- - TEXT[] is used for simple arrays such as repo topics and commit parent SHAs.
-- - Some GitHub API fields are renamed to avoid ambiguous names:
--   id -> user_id / repo_id / issue_id
--   type -> user_type
--   name -> user_name / repo_name
--   state -> issue_state

CREATE TABLE users (
	login TEXT,
	user_id BIGINT,
	node_id TEXT,
	avatar_url TEXT,
	gravatar_id TEXT,
	url TEXT,
	html_url TEXT,
	followers_url TEXT,
	following_url TEXT,
	gists_url TEXT,
	starred_url TEXT,
	subscriptions_url TEXT,
	organizations_url TEXT,
	repos_url TEXT,
	events_url TEXT,
	received_events_url TEXT,
	user_type TEXT,
	user_view_type TEXT,
	site_admin BOOLEAN,
	user_name TEXT,
	company TEXT,
	blog TEXT,
	user_location TEXT,
	email TEXT,
	hireable BOOLEAN,
	bio TEXT,
	twitter_username TEXT,
	public_repos INTEGER,
	public_gists INTEGER,
	followers INTEGER,
	user_following INTEGER,
	created_at TEXT,
	updated_at TEXT
);

CREATE TABLE repos (
	repo_id BIGINT,
	node_id TEXT,
	repo_name TEXT,
	full_name TEXT,
	private BOOLEAN,
	html_url TEXT,
	description TEXT,
	fork BOOLEAN,
	url TEXT,
	forks_url TEXT,
	keys_url TEXT,
	collaborators_url TEXT,
	teams_url TEXT,
	hooks_url TEXT,
	issue_events_url TEXT,
	events_url TEXT,
	assignees_url TEXT,
	branches_url TEXT,
	tags_url TEXT,
	blobs_url TEXT,
	git_tags_url TEXT,
	git_refs_url TEXT,
	trees_url TEXT,
	statuses_url TEXT,
	languages_url TEXT,
	stargazers_url TEXT,
	contributors_url TEXT,
	subscribers_url TEXT,
	subscription_url TEXT,
	commits_url TEXT,
	git_commits_url TEXT,
	comments_url TEXT,
	issue_comment_url TEXT,
	contents_url TEXT,
	compare_url TEXT,
	merges_url TEXT,
	archive_url TEXT,
	downloads_url TEXT,
	issues_url TEXT,
	pulls_url TEXT,
	milestones_url TEXT,
	notifications_url TEXT,
	labels_url TEXT,
	releases_url TEXT,
	deployments_url TEXT,
	created_at TEXT,
	updated_at TEXT,
	pushed_at TEXT,
	git_url TEXT,
	ssh_url TEXT,
	clone_url TEXT,
	svn_url TEXT,
	homepage TEXT,
	repo_size INTEGER,
	stargazers_count INTEGER,
	watchers_count INTEGER,
	repo_language TEXT,
	has_issues BOOLEAN,
	has_projects BOOLEAN,
	has_downloads BOOLEAN,
	has_wiki BOOLEAN,
	has_pages BOOLEAN,
	has_discussions BOOLEAN,
	forks_count INTEGER,
	mirror_url TEXT,
	archived BOOLEAN,
	disabled BOOLEAN,
	open_issues_count INTEGER,
	allow_forking BOOLEAN,
	is_template BOOLEAN,
	web_commit_signoff_required BOOLEAN,
	has_pull_requests BOOLEAN,
	pull_request_creation_policy TEXT,
	topics TEXT[],
	visibility TEXT,
	forks INTEGER,
	open_issues INTEGER,
	watchers INTEGER,
	default_branch TEXT,
	owner_id 	BIGINT,
	permissions_admin 	BOOLEAN,
	permissions_maintain 	BOOLEAN,
	permissions_push 	BOOLEAN,
	permissions_triage 	BOOLEAN,
	permissions_pull 	BOOLEAN,
	license_key 	TEXT,
	license_name 	TEXT,
	license_spdx_id 	TEXT,
	license_url 	TEXT,
	license_node_id 	TEXT
);

CREATE TABLE commits (
	sha TEXT,
	node_id TEXT,
	url TEXT,
	html_url TEXT,
	comments_url TEXT,
	repo_id BIGINT,
	repo_message TEXT,
	comment_count INTEGER,
	git_author_name TEXT,
	git_author_email TEXT,
	git_author_date TEXT,
	git_committer_name TEXT,
	git_committer_email TEXT,
	git_committer_date TEXT,
	author_login TEXT,
	author_id BIGINT,
	author_type TEXT,
	author_site_admin BOOLEAN,
	author_user_view_type TEXT,
	committer_login TEXT,
	committer_id BIGINT,
	committer_type TEXT,
	committer_site_admin BOOLEAN,
	committer_user_view_type TEXT,
	tree_sha TEXT,
	tree_url TEXT,
	verified BOOLEAN,
	verification_reason TEXT,
	verification_signature TEXT,
	verification_payload TEXT,
	verified_at TEXT,
	parent_shas TEXT[]
);

CREATE TABLE issues (
	url TEXT,
	repository_url TEXT,
	labels_url TEXT,
	comments_url TEXT,
	events_url TEXT,
	html_url TEXT,
	issue_id BIGINT,
	node_id TEXT,
	issue_number INTEGER,
	title TEXT,
	labels_json JSONB,
	issue_state TEXT,
	issue_locked BOOLEAN,
	assignees_json JSONB,
	milestone_json JSONB,
	issue_comments INTEGER,
	created_at TEXT,
	updated_at TEXT,
	closed_at TEXT,
	author_association TEXT,
	active_lock_reason TEXT,
	body TEXT,
	timeline_url TEXT,
	performed_via_github_app TEXT,
	state_reason TEXT,
	user_id BIGINT,
	repo_id BIGINT,
	sub_issues_summary_total INTEGER,
	sub_issues_summary_completed INTEGER,
	sub_issues_summary_percent_completed INTEGER,
	issue_dependencies_summary_blocked_by INTEGER, 
	issue_dependencies_summary_total_blocked_by INTEGER, 
	issue_dependencies_summary_blocking INTEGER,
	issue_dependencies_summary_total_blocking INTEGER,
	reaction_total_count INTEGER,
	reaction_plus INTEGER,
	reaction_minus INTEGER,
	reaction_laugh INTEGER,
	reaction_hooray INTEGER,
	reaction_confused INTEGER,
	reaction_heart INTEGER, 
	reaction_rocket INTEGER,
	reaction_eyes INTEGER,
	assignee_id BIGINT,
	assignee_login TEXT,
	assignee_type TEXT,
	assignee_site_admin BOOLEAN,
	closed_by_id BIGINT,
	closed_by_login TEXT,
	closed_by_type TEXT,
	closed_by_site_admin BOOLEAN
);




